### ISSUE TITLE
Update from 0.3.0 to 0.4.0 fails due to Tesla

### ISSUE THREAD

**Issue by thiagogsr** [ex-phone-number/ex_phone_number#66]
Hey folks

When we update this lib from version 0.3.0 to 0.4.0 it fails due to Tesla. 

```
==> ex_phone_number
Compiling 22 files (.ex)

== Compilation error in file lib/ex_phone_number/mix/tasks/update_metadata.ex ==
** (CompileError) lib/ex_phone_number/mix/tasks/update_metadata.ex:11: module Tesla is not loaded and could not be found
    (elixir 1.14.3) expanding macro: Kernel.use/1
    lib/ex_phone_number/mix/tasks/update_metadata.ex:11: Mix.Tasks.UpdateMetadata.GitHub (module)
could not compile dependency :ex_phone_number, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_phone_number", update it with "mix deps.update ex_phone_number" or clean it with "mix deps.clean ex_phone_number"
```

This dependency is declared in the lib, but only on dev and test, so I believe it's only installed on the lib development and testing, but not when it's imported in other project. Is this indented?

My project also has Tesla, but I believe it's compiled later by mix.

This is how the dependency is on `mix.lock`:

```
"ex_phone_number": {:hex, :ex_phone_number, "0.4.0", "2f9945be9f09bc892f9d50a504669dbe2cd590eb64ed110a2d8dbc551878337a", [:mix], [{:sweet_xml, "~> 0.7", [hex: :sweet_xml, repo: "hexpm", optional: false]}], "hexpm", "1a78506a19ee1d7bee511c81a8be35cca23053e519d6f47354926bd302aa202f"},
```

**Comment by szymon-jez** [comment]
Thanks for the detailed report. There is already a PR https://github.com/ex-phone-number/ex_phone_number/pull/65 which should fix this issue.
